plugins {
    id 'org.springframework.boot' version '4.1.1' apply false
    id 'org.sonarqube' version '7.3.1.8318'
}

group = 'com.nm.tranproc'
version = '1.0.0'

subprojects {

    apply plugin: 'java'
    apply plugin: 'jacoco'

    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testImplementation 'org.assertj:assertj-core'
        testImplementation 'org.mockito:mockito-core'
    }

    tasks.named('test') {
        useJUnitPlatform()
        finalizedBy tasks.named('jacocoTestReport')
    }

    jacoco {
        toolVersion = '0.8.14'
    }

    tasks.named('jacocoTestReport') {
        dependsOn tasks.named('test')

        reports {
            xml.required = true
            html.required = true
            csv.required = false
        }
    }

    tasks.named('jacocoTestCoverageVerification') {
        violationRules {
            rule {
                limit {
                    counter = 'LINE'
                    value = 'COVEREDRATIO'
                    minimum = 0.80
                }
            }

            rule {
                limit {
                    counter = 'BRANCH'
                    value = 'COVEREDRATIO'
                    minimum = 0.70
                }
            }
        }
    }

    tasks.named('check') {
        dependsOn tasks.named('jacocoTestCoverageVerification')
    }
}